CREATE TABLE KPCU (
  Txn_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  "Date" Date NOT NULL ENABLE,
  Description VARCHAR(45),
  Amount NUMBER (7,2),
  Balance NUMBER (7,2) NOT NULL ENABLE,
CONSTRAINT "KPCU_PK" PRIMARY KEY (Txn_ID));
